#LISTA DE EXERCICIOS REFERENTES AS SOLUÇÕES NESTA REPOSITÓRIO!
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
#https://wiki.python.org.br/EstruturaDeDecisao
